### ISSUE TITLE
Improve command usage descriptions

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/cli#108]
One simple sentence is most of the time not enough to describe what the command does.

**Comment by philippgille** [comment]
It would also be nice to know which flags are required and which aren't. For example:

```bash
$ hcloud server create -h
Create a server

Usage:
  hcloud server create FLAGS

Flags:
      --datacenter string            Datacenter (ID or name)
  -h, --help                         help for create
      --image string                 Image (id or name)
      --location string              Location (ID or name)
      --name string                  Server name
      --ssh-key strings              ID or name of SSH key to inject (can be specified multiple times)
      --type string                  Server type (id or name)
      --user-data-from-file string   Read user data from specified file (use - to read from stdin)
```

Doesn't show which flags are required. Only when trying to create a server *without* the required flags, there's a notification about the required ones:

```bash
$ hcloud server create
hcloud: required flag(s) "image", "name", "type" not set
```

**Comment by hubitor** [comment]
Another example of the implications of the lack of documentation:

I was trying to find out how can I add an SSH key to HETZNER, but there was not something like **add** in the available commands. 

I had to spent some time experimenting with the **create** command to find out how it works.

The description of **create** is this:
**create       Create a SSH key**
which I find misleading, since no SSH key is being created. I think something like **add** would be more accurate.
