### ISSUE TITLE
Allow to pass options to ssh command

### ISSUE THREAD

**Issue by svenstaro** [hetznercloud/cli#113]
I would like to pass options to the ssh invocation when doing `hcloud server ssh`.

**Comment by thcyron** [comment]
Is there a specific option you want to specify (like port) or do you want to pass arbitrary options?

Since there’s already a flag `--user` for `hcloud server ssh` I’m unsure if adding another flag to pass *any* option for `ssh` is a good idea. I’d rather have specific flags and allow something like this for more complex use cases:

```
ssh -l foo -p 1234 -o MyOption=yes $(hcloud server ip server.example.com) uptime
```

**Comment by svenstaro** [comment]
Sometimes I rapidly kill and recreate servers and that makes me want to ignore ssh host key checking for debugging purposes because having to edit my known hosts is annoying. This happens if get the same server IP twice in a row. 

However, I imagine there are other use cases as well.

**Comment by exquisitus** [comment]
At our company, we would use a `--port` option for `hcloud server ssh`, if it were available.

**Comment by thcyron** [comment]
I’m fine with adding a `-p/--port` flag.

Now that we have labels, what about introducing a special label which specifies the SSH port to use by the CLI? Something like:

```
hcloud server add-label test cli.hetzner.cloud/ssh-port=2222
hcloud server ssh test  # connects to port 2222
```

Just an idea – not necessarily a good one.
