### ISSUE TITLE
[BUG] config file path unknown?

### ISSUE THREAD

**Issue by soakes** [hetznercloud/cli#114]
Hi,

I am trying to use the 1.5.0 release within a docker container (amd64).

I have done the following (this is just an early test to get hcloud cli working first before I add the rest of the code):

```
FROM netspeedy/alpine
LABEL maintainer="*****"
LABEL description="Keepalived VIP with notify and hetzner cli support"

RUN set -x \
    && apk update && apk add --no-cache \
        openssl \
        ca-certificates \
    && mkdir -p /app/hetzner \
    && wget -qO - https://github.com/hetznercloud/cli/releases/download/v1.5.0/hcloud-linux-amd64-v1.5.0.tar.gz \
         | tar --strip 1 -zxC /app/hetzner \
    && update-ca-certificates

ENTRYPOINT ["/init"]
```
But when trying to run hcloud with say:

```
$ /app/hetzner/bin/hcloud context create test
Token:
hcloud: config file path unknown
```
It retuns: `hcloud: config file path unknown`

I have also tried to copy my config from laptop which is in ~/.config/hcloud to the image and it does the same.  

I have looked and can't seem to find away to set the path of the config.   What am I doing wrong?

My laptop `brew` installed version works fine.

Any assistance would be greatly appreciated.

Kind Regards,

Simon

**Comment by thcyron** [comment]
The error message “config file path unknown” is returned when either the current user could not be determined (using [user.Current](https://golang.org/pkg/os/user/#Current)) or the home directory is undefined. I think the latter is more likely.

However, you can specify the config file path manually using `HCLOUD_CONFIG`. For scripts, instead of creating a context, you can also just set `HCLOUD_TOKEN`.

**Comment by soakes** [comment]
@thcyron Thanks very much for the solutions.

**Comment by computersrmyfriends** [comment]
Where to use the HCLOUD_CONFIG or HCLOUD_TOKEN?

**Comment by soakes** [comment]
Hi there,

Its just an ENV var..  so
export HCLOUD_TOKEN="BLAH"

Kind Regards
