### ISSUE TITLE
Planned maintenance information

### ISSUE THREAD

**Issue by rapli** [hetznercloud/cli#137]
It is essential to be able to automate proper reactions on planned maintenances of cloud nodes, e.g. failover or a planned service shutdown. Therefore the hcloud tool (and the thus also the Hetzner Cloud API) should provide additional information for each server, definitely in the "server describe" command, eventually also in the server list. 
- cloud node id - the server's cloud node
- planned maintenance start - timestamp of the next upcoming planned maintenance
- planned maintenance end - timestamp of the planned maintenance's end
- planned maintenance information - additional information on the maintenance (as also can be found on the hetzner status website)

This information could be placed within a new "cloud node" object.

**Comment by avlapshin** [comment]
In fact, at least the cloud node ID in the server information is sufficient. Because the currently proposed method for determining the cloud node ID using _mtr_ is extremely long and cannot be used in automated environments due to timeout limitations. The remaining information is desirable, but not required. It can be obtained from the site _hetzner-status.de_ using the `affected` field.

**Comment by igorcoding** [comment]
Please don't

**Comment by LKaemmerling** [comment]
Actually, we don't have a way how we can give this information out. There is some work ongoing which will improve the status notification situation, but we can not integrate this into the cli. So I will close this issue. If there is a way how we can improve the situation we will do this.
