### ISSUE TITLE
hcloud commands fail frequently because of server errors

### ISSUE THREAD

**Issue by fho** [hetznercloud/cli#249]
We use `hcloud` in CI jobs to create VMs to run tests.
`hcloud` commands now and then fail with errors like:

- `hcloud: server responded with status code 503`
- `hcloud: Creating server failed because of an unknown error. (unknown_error)`
- `hcloud:  (server_error)`
- `hcloud: Creating image failed because of an unknown error. (unknown_error)`

This causes  that our CI pipelines fail and we have to rerun the whole pipelines.

The best solution would be to fix the error cause at the hcloud endpoint and have it 100% reliable.
This might be difficult to achieve though. :-)

Another solution to make hcloud operations more reliable could be to implement a retry mechanism in hcloud. If an operation fails with a temporary error, the tool could retry the operation until a timeout expire.

**Comment by LKaemmerling** [comment]
Could you please write a Support ticket for this? Actually this looks like problems on the Host system (the unkown_errors). When the 503 and/or the `server_error` occur we don't want to retry because this can cause problems (or might power up existing problems). 

This is not hcloud-cli specific, so i will close the issue here.
