### ISSUE TITLE
Error when trying to get version of hcloud

### ISSUE THREAD

**Issue by Giom-fm** [hetznercloud/cli#369]
When I try to get the version of the tool I get the following error message: hcloud was not built properly

**Comment by LKaemmerling** [comment]
Hey @Giom-fm,

how did you install the hcloud cli?

**Comment by Giom-fm** [comment]
I build it myself by cloning the repo and using go build command.
No errors or warnings were displayed.

go1.17.3 linux/amd64 on debian sid

**Comment by LKaemmerling** [comment]
Hey @Giom-fm,

then this is the reason :) The string you mentioned is the default (https://github.com/hetznercloud/cli/blob/master/internal/version/version.go#L4) within our build script in CI we set this version to the correct git tag (https://github.com/hetznercloud/cli/blob/master/.goreleaser.yml#L6) . Because you don't use our prebuild binaries you see this "error".

**Comment by Giom-fm** [comment]
Ah I see!
All right then I can set the string myself.
Thanks for the help @LKaemmerling!

**Comment by Baryczka** [comment]
@LKaemmerling  Installing version from ubuntu repo focal giving the same result: `hcloud was not built properly`

**Comment by Giom-fm** [comment]
Yes the same on Debian.
Moreover, the version on debian is severely outdated. This is the reason why I now maintain the package under [MPR](https://mpr.hunterwittenborn.com/).
