### ISSUE TITLE
hcloud server list -o json represents a missing IPv6 as "<nil>"

### ISSUE THREAD

**Issue by martinvonwittich** [hetznercloud/cli#397]
One of our newly created VMs was accidentally created without an IPv6.

`hcloud` has a very... unique way of representing the missing IPv6 - with `"ip": "<nil>"`:

```
  {
    "id": 22282945,
    "name": "<redacted>",
    "status": "running",
    "created": "2022-07-21T06:35:13Z",
    "public_net": {
      "ipv4": {
        "id": 0,
        "ip": "<redacted>",
        "blocked": false,
        "dns_ptr": "<redacted>"
      },
      "ipv6": {
        "id": 0,
        "ip": "<nil>",
        "blocked": false,
        "dns_ptr": null
      },
      "floating_ips": null,
      "firewalls": null
    },
```

I think `"ip": null`, or completely removing the `"ipv6"` key from the object would be preferable.

**Comment by LKaemmerling** [comment]
This is basically a tradeoff we needed to make. When we "null" the "ipv6" key it is a breaking change in the API. Because of this we have within our own SDKs functions like https://github.com/hetznercloud/hcloud-go/blob/main/hcloud/server.go#L120 . There is sadly no great way around it without introducing a breaking change.
