### ISSUE TITLE
hcloud: unable to authenticate (unauthorized) with correct token

### ISSUE THREAD

**Issue by papanito** [hetznercloud/cli#410]
I have two contexts

- production
- development

I have a token for each context -  they are correct and of 64bit length

- development = `YSSH...`
- production = `K3vt...`

![image](https://user-images.githubusercontent.com/15034009/187899765-6b7563fb-326b-4fd8-821b-79e1d5956977.png)

## Non-working context

1. I set `HCLOUD` to `YSSH...`
2. I am in the correct contect 

   ```
   $ hcloud context list
   ACTIVE   NAME
   *        development
            production
   ```

3. Run `hcloud server list` 

   ```bash
   $hcloud server list
   hcloud: unable to authenticate (unauthorized)
   ```

**--> I would expect this to work**

I even tried creating a new token, same result

## Working context

1. I set `HCLOUD` to `K3vt...`
2. I switch the contect

   ```
   $ hcloud context list
   ACTIVE   NAME
            development
   *        production
   ```

3. Run `hcloud server list` 

   ```bash
   $hcloud server list
   ID        NAME    STATUS    IPV4             IPV6                     PRIVATE NET   DATACENTER
   xxxxxx    ttrss   running   xx.xxx.xxx.xxx   xxxx:xxx:xxxx:xxx::/64   -             hel1-dc2
   ```

**--> works as expected**

## Version

```
$ hcloud version
hcloud 1.30.3
```

**Comment by papanito** [comment]
Still have this issue

**Comment by apricote** [comment]
Hey @papanito,

two things I noticed while reading your issue:

- You say that you set `HCLOUD` to the token, but the environment variable must be named `HCLOUD_TOKEN`
- You only need to use either the environment variable OR a profile. The profile already has the token from when you created the profile.

Based on these two, I assume that your profile `development` has a invalid token (maybe you revoked it), and because you use the wrong environment variable to override the token, `hcloud` uses the invalid token from the profile.

I would suggest you create a new profile with the correct token for development and try using that without setting an environment variable.

**Comment by papanito** [comment]
> You say that you set `HCLOUD` to the token, but the environment variable must be named `HCLOUD_TOKEN`
duh, thanks for the hint, did that change or was it always like that? It's a while ago I used the cli and while migrating my dotfiles, I may have missed something. Still strange it worked for one context and the other not.

I tried now with both original tokens, setting them to `HCLOUD_TOKEN` and I can access both context as expected. Not sure what I did wrong, but I will close the issue. Thanks @apricote
