### ISSUE TITLE
hcloud server create does not use standard keys from cloud console

### ISSUE THREAD

**Issue by schwarmco** [hetznercloud/cli#425]
There is an option in Hetzner Cloud Console to set an SSH key as "default" so when you create a new server via Cloud Console, it adds all flagged SSH keys as authorized keys.

Inspecting the request in Cloud Console shows, that these SSH keys have `is_default: true` set but this option is not specified in the API docs (https://docs.hetzner.cloud/#ssh-keys-get-all-ssh-keys)

When using `hcloud server create` these keys do not get added as authorized keys, which i would have expected. If this is intended, something like a `--use-default-ssh-keys` cli option would be great instead.

**Comment by LKaemmerling** [comment]
Hey @schwarmco,

thank you for your required. The property is not exposed to the public API on purpose as it would turn into a possible security or understanding issue for our customers. When we added this "feature" to our Cloud Console we thought a lot about it as there are several ways to implement it. In the Cloud Console you have this as a "preselecting", so per default, they are selected in the Cloud Console on the Creation of the server. You can easily check and prove that the selected keys should be on this server. However, on the CLI on the other hand this would be a bit more difficult. Of course, we could use a flag as you proposed but this then would lead to "understanding" issues. If a key is marked as `is_default=true` I would expect that it is added on every server without me doing something. Because of the security aspect, this is something we don't want to do because just imagine your SSH Key was selected as a default - and now you leave the company - then you would have still access to all new servers - until someone deletes/updates your SSH Key. So there is basically no visual confirmation when creating the server. 

This is basically the reason why we decided against exposing it and using it as a Frontend (Cloud Console) Only Feature.

But you can achieve your usecase already quite easily by using labels on the SSH Key:
```sh
hcloud ssh-key add-label your-key default=true

hcloud server create \
  --name ssh-keys-selector \
  --image ubuntu-22.04 \
  --location hel1 \
  --type cpx11 \
  --ssh-key $(hcloud ssh-key list --selector=default=true -o=columns=id -o=noheader | tr '\n' ',' | head -c -1)
  ```

But I (personally) would suggest using this "automation" only If you are confident that the keys are exactly the ones you expect them to be.

**Comment by schwarmco** [comment]
Hi @LKaemmerling - thank you very much for that detailed explanation and the workaround!
