### ISSUE TITLE
cloud-init support when creating server

### ISSUE THREAD

**Issue by dummys** [hetznercloud/cli#83]
Hi, is the option --user-data supported when creating server ?

**Comment by thetechnick** [comment]
Hi,
not yet but I will take care of it.

As discussed with @thcyron:
New flag `--user-data-from-file`, when specifying `-` read from Stdin.

@dummys Does this solve your use case?

**Comment by dummys** [comment]
yes and when using `--user-data-from-file file_name` it will be read from a json file right ?

**Comment by thetechnick** [comment]
For cloud-init to work you need to provide the data in one of the documented formats:
https://cloudinit.readthedocs.io/en/latest/topics/format.html#cloud-config-data

**Comment by dummys** [comment]
Oups yes sorry not json but yml. typo

**Comment by thetechnick** [comment]
The userdata just has to be a valid json string.
So if this is your cloud config:

```yaml
#cloud-config
runcmd:
- [touch, /root/cloud-init-worked-yay]
```

the json API request will look something like this:

```json
{
  "name": "my-cool-server",
  "server_type": "cx11",
  "image": "debian-9",
  "user_data": "#cloud-config\nruncmd:\n- [touch, /root/cloud-init-worked-yay]\n"
}
```

**Comment by dummys** [comment]
ok thanks. when did you think this will be available il hcloud ?

**Comment by thetechnick** [comment]
I am writing the code just now :)

**Comment by dummys** [comment]
@thetechnick thanks a lot for the features

**Comment by gerwinbrunner** [comment]
Does this option also exist for server rebuil ?

**Comment by thcyron** [comment]
No. Passing user data when rebuilding a server is not supported in general.

**Comment by Patrick-Remy** [comment]
Just as a hint for anybody encountering this problem:

`/var/log/cloud-init-output.log ` 
```
__init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b'runcmd:'...'
/usr/lib/python3/dist-packages/cloudinit/config/cc_rsyslog.py:205: FutureWarning: Possible nested set at position 23
  r'^(?P<proto>[@]{0,2})'
```

Ensure your config file is starting with `#cloud-config` just as described in https://cloudinit.readthedocs.io/en/latest/topics/format.html#cloud-config-data and it just works ;)

**Comment by Radiergummi** [comment]
@thetechnick, @thcyron regarding @Patrick-Remy's hint: Would it be possible to check the user-provided cloud config for whether it starts with this comment, and add it if missing? It's _extremely_ annoying if the cloud init configuration doesn't run because I omitted a freaking comment inserted into a textarea in a web interface. Argh.

**Comment by apricote** [comment]
`cloud-init` supports multiple formats that can be passed, one is `#cloud-config`, another one would be scripts where the first line needs to start with `#!`.

As we don't know which format the user passed, we can not just add the comment.

**Comment by Radiergummi** [comment]
Initially, I wanted to suggest validating user data based on the OS and whether the script looks like valid YAML, but I realised this is prone to errors, and the current approach makes sense. It isn't even a documentation issue, because it's all written very clearly once one actually reads the [linked documentation](https://community.hetzner.com/tutorials/basic-cloud-config/de). So my apologies for taking up your time, and thank you for the calm reply :)
